# MediMeal Application Configuration
base.url=http://localhost:3000
browser=chrome
implicit.wait=10
explicit.wait=20

# Admin Credentials
admin.email=admin@medimeal.com
admin.password=medi123

# Doctor Credentials
doctor.email=siya@doctor-medi.com
doctor.password=medi123

# Patient Credentials
patient.email=tessasaji26@mca.ajce.in
patient.password=medi123
