const PDFDocument = require('pdfkit');

function formatCurrencyINR(amount) {
  const n = Number(amount || 0);
  return `₹${n.toFixed(2)}`;
}

function safeText(v) {
  return String(v ?? '').trim();
}

/**
 * Generate an invoice PDF as a Buffer.
 */
async function generateInvoicePdf({ invoice, user, appointment }) {
  return await new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 48 });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Header
      doc
        .fontSize(20)
        .text('MediMeal', { align: 'left' })
        .moveDown(0.25);
      doc
        .fontSize(12)
        .fillColor('#444444')
        .text('Healthcare Invoice', { align: 'left' })
        .fillColor('#000000')
        .moveDown(1);

      // Invoice meta
      doc.fontSize(11);
      doc.text(`Invoice Number: ${safeText(invoice.invoiceNumber)}`);
      doc.text(`Invoice Date: ${new Date(invoice.invoiceDate || invoice.createdAt || Date.now()).toLocaleString()}`);
      doc.text(`Transaction ID: ${safeText(invoice.transactionId)}`);
      if (appointment?.status) doc.text(`Payment Status: ${safeText(String(appointment.status).toUpperCase())}`);
      doc.moveDown(1);

      // Bill to
      doc.fontSize(12).text('Bill To', { underline: true });
      doc.fontSize(11);
      doc.text(safeText(`${user?.firstName || ''} ${user?.lastName || ''}`) || safeText(user?.email) || 'User');
      if (user?.email) doc.text(safeText(user.email));
      doc.moveDown(1);

      // Appointment details
      doc.fontSize(12).text('Appointment Details', { underline: true });
      doc.fontSize(11);
      doc.text(`Doctor: ${safeText(invoice.doctorName) || safeText(appointment?.provider?.name) || 'Doctor'}`);
      if (invoice.doctorSpecialization) doc.text(`Specialization: ${safeText(invoice.doctorSpecialization)}`);
      if (appointment?.appointmentDate) {
        doc.text(`Appointment Date: ${new Date(appointment.appointmentDate).toLocaleString()}`);
      }
      if (appointment?.type) doc.text(`Type: ${safeText(appointment.type)}`);
      doc.moveDown(1);

      // Amounts table (simple)
      const fee = Number(invoice.consultationFee || 0);
      const tax = Number(invoice.tax || 0);
      const total = Number(invoice.totalAmount || fee + tax);

      doc.fontSize(12).text('Charges', { underline: true });
      doc.moveDown(0.5);

      const leftX = doc.x;
      const rightX = 520;

      const lineItem = (label, value) => {
        doc.fontSize(11).text(label, leftX, doc.y, { continued: false });
        doc.fontSize(11).text(value, rightX - 120, doc.y - 14, { width: 120, align: 'right' });
      };

      lineItem('Consultation Fee', formatCurrencyINR(fee));
      lineItem(`Tax (GST ${(Number(invoice.taxRate || 0.18) * 100).toFixed(0)}%)`, formatCurrencyINR(tax));

      doc.moveDown(0.25);
      doc.moveTo(leftX, doc.y).lineTo(rightX, doc.y).strokeColor('#dddddd').stroke();
      doc.moveDown(0.5);

      doc.fontSize(12).text('Total', leftX, doc.y, { continued: false });
      doc.fontSize(12).text(formatCurrencyINR(total), rightX - 120, doc.y - 14, { width: 120, align: 'right' });
      doc.moveDown(2);

      doc
        .fontSize(10)
        .fillColor('#666666')
        .text('Thank you for using MediMeal!', { align: 'center' })
        .text('This is an automated invoice generated by the MediMeal system.', { align: 'center' })
        .fillColor('#000000');

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

module.exports = { generateInvoicePdf };

